name: DevSecOps Security Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  security:
    name: Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Audit NPM packages
        run: npm audit --production

      - name: Dependency Review
        uses: actions/dependency-review-action@v3

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test
